_commit: v2.0.0
_src_path: gh:superlinear-ai/substrate
author_email: seanchatmangpt@gmail.com
author_name: seanchatmangpt
project_description: KCJ Multi-Lingual MuStar League
project_name: kcj-mustar
project_type: package
project_url: https://github.com/seanchatmangpt/kcj-mustar
python_version: '3.12'
typing: optional
with_conventional_commits: true
with_typer_cli: false
